kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
        - name: locust
          image: tfwiki/locust:latest
          imagePullPolicy: Always
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              value: https://prod.wiki.tf
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
