kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: locust-worker
  labels:
    name: locust
    role: worker
spec:
  replicas: 100
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust
          image: tfwiki/locust:latest
          imagePullPolicy: Always
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: https://prod.wiki.tf
            - name: LOCUST_MODEL
              value: pyromania
